export type InputType = 'text' | 'buttons' | 'date' | 'time' | 'image' | 'mixed';

export interface Step {
    id: string;
    text?: string; // Text is now optional if we just want to send an image
    imageArg?: string; // URL or placeholder for an image sent BY THE BOT
    buttons?: string[];
    inputType?: InputType;
    next?: (answer: string) => string;
    saveField?: string;
    isMultiSelect?: boolean;
}

export const FLOW_IDS = {
    WELCOME: 'WELCOME',
    CATEGORY: 'CATEGORY',

    // Categories (keeping existing IDs)
    CLEANING_CITY: 'CLEANING_CITY',
    CLEANING_AREA: 'CLEANING_AREA',
    CLEANING_FREQ: 'CLEANING_FREQ',
    CLEANING_FREQ_OTHER: 'CLEANING_FREQ_OTHER',
    CLEANING_DAYS: 'CLEANING_DAYS',
    CLEANING_TIME: 'CLEANING_TIME',
    CLEANING_SIZE: 'CLEANING_SIZE',
    CLEANING_EXTRAS: 'CLEANING_EXTRAS',
    CLEANING_NOTES: 'CLEANING_NOTES',
    CLEANING_LANG: 'CLEANING_LANG',
    CLEANING_LANG_OTHER: 'CLEANING_LANG_OTHER',
    CLEANING_ALLERGY: 'CLEANING_ALLERGY',
    CLEANING_DONE: 'CLEANING_DONE',

    NANNY_CITY: 'NANNY_CITY',
    NANNY_DAYS: 'NANNY_DAYS',
    NANNY_HOURS: 'NANNY_HOURS',
    NANNY_HOURS_OTHER: 'NANNY_HOURS_OTHER',
    NANNY_AGES: 'NANNY_AGES',
    NANNY_CAR: 'NANNY_CAR',
    NANNY_TASKS: 'NANNY_TASKS',
    NANNY_TASKS_OTHER: 'NANNY_TASKS_OTHER',
    NANNY_NOTES: 'NANNY_NOTES',
    NANNY_ALLERGY: 'NANNY_ALLERGY',
    NANNY_LANG: 'NANNY_LANG',
    NANNY_LANG_OTHER: 'NANNY_LANG_OTHER',
    NANNY_DONE: 'NANNY_DONE',

    BABY_CITY: 'BABY_CITY',
    BABY_WHEN: 'BABY_WHEN',
    BABY_DATE: 'BABY_DATE',
    BABY_HOURS: 'BABY_HOURS',
    BABY_HOURS_OTHER: 'BABY_HOURS_OTHER',
    BABY_COUNT: 'BABY_COUNT',
    BABY_AGES: 'BABY_AGES',
    BABY_TYPE: 'BABY_TYPE',
    BABY_REQ: 'BABY_REQ',
    BABY_NOTES: 'BABY_NOTES',
    BABY_NOTES_TEXT: 'BABY_NOTES_TEXT',
    BABY_DONE: 'BABY_DONE',

    FOOD_CITY: 'FOOD_CITY',
    FOOD_FREQ: 'FOOD_FREQ',
    FOOD_TIME: 'FOOD_TIME',
    FOOD_TIME_OTHER: 'FOOD_TIME_OTHER',
    FOOD_PEOPLE: 'FOOD_PEOPLE',
    FOOD_STYLE: 'FOOD_STYLE',
    FOOD_STYLE_OTHER: 'FOOD_STYLE_OTHER',
    FOOD_KOSHER: 'FOOD_KOSHER',
    FOOD_NOTES: 'FOOD_NOTES',
    FOOD_NOTES_OTHER: 'FOOD_NOTES_OTHER',
    FOOD_GOAL: 'FOOD_GOAL',
    FOOD_GOAL_OTHER: 'FOOD_GOAL_OTHER',
    FOOD_DONE: 'FOOD_DONE',

    GARDEN_CITY: 'GARDEN_CITY',
    GARDEN_TYPE: 'GARDEN_TYPE',
    GARDEN_TASK: 'GARDEN_TASK',
    GARDEN_TASK_OTHER: 'GARDEN_TASK_OTHER',
    GARDEN_FREQ: 'GARDEN_FREQ',
    GARDEN_TOOLS: 'GARDEN_TOOLS',
    GARDEN_ACCESS: 'GARDEN_ACCESS',
    GARDEN_PHOTO: 'GARDEN_PHOTO',
    GARDEN_PHOTO_UPLOAD: 'GARDEN_PHOTO_UPLOAD',
    GARDEN_DONE: 'GARDEN_DONE',

    // === Phase 3: Match ===
    MATCH_FOUND_PREFIX: 'MATCH_FOUND_PREFIX',
    MATCH_CARD_1_IMG: 'MATCH_CARD_1_IMG', // New image step
    MATCH_CARD_1: 'MATCH_CARD_1',
    MATCH_CARD_1_RECS: 'MATCH_CARD_1_RECS', // Recommendations

    // === Phase 4: Scheduling ===
    SCHEDULE_WHEN: 'SCHEDULE_WHEN',
    SCHEDULE_WHEN_OTHER: 'SCHEDULE_WHEN_OTHER',
    SCHEDULE_ADDRESS: 'SCHEDULE_ADDRESS',
    SCHEDULE_CONFIRM: 'SCHEDULE_CONFIRM',
    SCHEDULE_DONE: 'SCHEDULE_DONE',

    // === Phase 5: Feedback & Backup ===
    FEEDBACK_START: 'FEEDBACK_START',
    FEEDBACK_PUNCTUALITY: 'FEEDBACK_PUNCTUALITY',
    FEEDBACK_CONTINUE: 'FEEDBACK_CONTINUE',
    FEEDBACK_SETUP_REGULAR: 'FEEDBACK_SETUP_REGULAR',

    // Backup / Alternatives
    BACKUP_OFFER_IMG_1: 'BACKUP_OFFER_IMG_1',
    BACKUP_OFFER_CARD_1: 'BACKUP_OFFER_CARD_1',
    BACKUP_OFFER_IMG_2: 'BACKUP_OFFER_IMG_2',
    BACKUP_OFFER_CARD_2: 'BACKUP_OFFER_CARD_2',

    NOT_SUITABLE_OFFER: 'NOT_SUITABLE_OFFER', // Legacy, kept for safety
    CANCEL_OFFER: 'CANCEL_OFFER',
    CANCEL_SEARCHING: 'CANCEL_SEARCHING'
};
